version: "3.8"
services:
  one:
    build:
      context: ./one
      dockerfile: Dockerfile
    image: one:latest
    ports:
      - "8081:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
  two:
    build:
      context: ./two
      dockerfile: Dockerfile
    image: two:latest
    ports:
      - "8082:8080"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
